// src/components/WorldMap.tsx
import React, { useEffect, useMemo, useRef, useState } from "react"

import { countryCoordinates } from "@/lib/geo-limit"
import { cn } from "@/lib/utils"
import { count2size, findIntersectingGroups, lonLatToMapXY } from "@/lib/world-map"

import WorldMapPoint from "./WorldMapPoint"

type LocationInput = {
  key: string
  count: number
  label: string
  servers: { id: number; name: string }[]
  lng: number
  lat: number
}

function computeDetailContainerWidth() {
  const w = window.innerWidth
  if (w <= 720) return w
  if (w <= 800) return 720
  if (w <= 1024) return 800
  return 900
}

function computeWorldMapWidth() {
  return Math.max(computeDetailContainerWidth() - 40, 300)
}

export default function WorldMap({
  locations,
  className,
}: {
  locations: LocationInput[]
  className?: string
}) {
  const [mapWidth, setMapWidth] = useState<number>(() => (typeof window === "undefined" ? 900 : computeWorldMapWidth()))

  useEffect(() => {
    const handleResize = () => setMapWidth(computeWorldMapWidth())
    handleResize()
    window.addEventListener("resize", handleResize)
    return () => window.removeEventListener("resize", handleResize)
  }, [])

  const mapHeight = useMemo(() => Math.ceil((621 / 1280) * (Number(mapWidth) || 0)), [mapWidth])

  const points = useMemo(() => {
    const boxPadding = 0
    if (!Array.isArray(locations) || locations.length === 0) return []

    const pts = locations.map((loc) => {
      const { x, y } = lonLatToMapXY(loc.lng, loc.lat)
      const left = (mapWidth / 1280) * x + boxPadding
      const top = (mapHeight / 621) * y + boxPadding
      const size = count2size(loc.count)
      const item: any = {
        key: loc.key,
        left,
        top,
        size,
        label: loc.label,
        servers: loc.servers,
        type: "single",
      }
      const halfSize = (item.size + 8) / 2
      item.topLeft = { left: item.left - halfSize, top: item.top - halfSize }
      item.bottomRight = { left: item.left + halfSize, top: item.top + halfSize }
      return item
    })

    const groups = findIntersectingGroups(pts)
    Object.entries(groups).forEach(([key, group]) => {
      const item = pts.find((i) => i.key === key)
      if (!item || item.parent) return
      item.size = 4
      item.type = "group"
      item.children = group
      let label = item.label || ""
      let servers = [...(item.servers || [])]
      group.forEach((g: any) => {
        if (!g.parent && !g.children) {
          g.parent = item
          label += `\n${g.label}`
          servers = servers.concat(g.servers || [])
        }
      })
      item.label = label
      item.servers = servers
    })

    return pts.filter((i) => !i.parent)
  }, [locations, mapWidth, mapHeight])

  const [tipsShow, setTipsShow] = useState(false)
  const [tipsContent, setTipsContent] = useState("")
  const [activeXY, setActiveXY] = useState({ x: 0, y: 0 })
  const tipsTimer = useRef<number | null>(null)

  function handleTap(info: any) {
    setTipsContent(info.label || "")
    setActiveXY({ x: info.left, y: info.top - 10 })
    setTipsShow(true)
    if (tipsTimer.current) {
      window.clearTimeout(tipsTimer.current)
    }
    tipsTimer.current = window.setTimeout(() => setTipsShow(false), 5000)
  }

  useEffect(
    () => () => {
      if (tipsTimer.current) window.clearTimeout(tipsTimer.current)
    },
    [],
  )

  const tipsStyle = useMemo(() => {
    if (typeof window !== "undefined" && window.innerWidth <= 500) {
      return { bottom: "4px", left: "50%", transform: "translate(-50%, 0)" }
    }
    return { top: `${activeXY.y}px`, left: `${activeXY.x}px`, transform: "translate(-50%, 20px)" }
  }, [activeXY])

  return (
    <div
      className={cn("world-map-group", className)}
      style={
        {
          "--world-map-width": `${mapWidth}px`,
          "--world-map-height": `${mapHeight}px`,
        } as React.CSSProperties
      }
    >
      <div className="world-map-img" />
      <div className="world-map-point-container">
        {points.map((p) => (
          <WorldMapPoint key={p.key} info={p} onTap={handleTap} />
        ))}
      </div>
      {tipsShow && (
        <div className="world-map-tips" style={tipsStyle as React.CSSProperties}>
          <span>{tipsContent}</span>
        </div>
      )}
    </div>
  )
}

export function buildLocationsFromServers(servers: { id: number; name: string; country_code?: string; online?: boolean | number }[]) {
  const map = new Map<string, { count: number; servers: { id: number; name: string }[] }>()
  servers.forEach((s) => {
    const isOnline = s.online === true || s.online === 1
    if (!isOnline) return
    const code = (s.country_code || "").toUpperCase()
    if (!code) return
    if (!countryCoordinates[code]) return
    const prev = map.get(code) || { count: 0, servers: [] }
    prev.count += 1
    prev.servers.push({ id: s.id, name: s.name })
    map.set(code, prev)
  })

  const locations: LocationInput[] = []
  map.forEach((v, code) => {
    const coord = countryCoordinates[code]
    locations.push({
      key: code,
      count: v.count,
      servers: v.servers,
      lng: coord.lng,
      lat: coord.lat,
      label: `${coord.name},${v.count}台`,
    })
  })
  return locations
}

// src/components/world-map/world-map.vue
<template>
  <div
    class="world-map-group"
    :style="mapStyle"
  >
    <div class="world-map-img" />
    <transition-group
      name="point"
      tag="div"
      class="world-map-point-container"
    >
      <world-map-point
        v-for="pointItem in mapPoints"
        :key="pointItem.key"
        :info="pointItem"
        @point-tap="handlePointTap"
      />
    </transition-group>

    <transition name="point">
      <div
        v-if="tipsShow"
        class="world-map-tips"
        :style="tipsContentStyle"
      >
        <span>{{ tipsContent }}</span>
      </div>
    </transition>
  </div>
</template>

<script setup>
/**
 * 世界地图盒子
 */

import {
  ref,
  computed,
  watch,
} from 'vue';
import validate from '@/utils/validate';

import WorldMapPoint from './world-map-point.vue';
import {
  findIntersectingGroups,
} from '@/utils/world-map';

const props = defineProps({
  width: {
    type: [Number, String],
    // default: 1280,
    default: null,
  },
  height: {
    type: [Number, String],
    // default: 621,
    default: null,
  },
  locations: {
    type: Array,
    default: () => [],
  },
});

const boxPadding = 0;

// 计算地图大小 保持1280:621的比例 保证地图不变形
const computedSize = computed(() => {
  if (validate.isEmpty(props.width) && validate.isEmpty(props.height)) {
    return {
      width: 1280,
      height: 621,
    };
  }

  // 考虑内边距，从总宽高中减去padding
  const adjustedWidth = Number(props.width) - (boxPadding * 2);
  const adjustedHeight = Number(props.height) - (boxPadding * 2);

  if (!validate.isEmpty(props.width) && !validate.isEmpty(props.height)) {
    return {
      width: 1280,
      height: 621,
    };
  }

  if (!validate.isEmpty(props.width) && validate.isEmpty(props.height)) {
    return {
      width: adjustedWidth,
      height: Math.ceil((621 / 1280) * adjustedWidth),
    };
  }

  if (validate.isEmpty(props.width) && !validate.isEmpty(props.height)) {
    return {
      width: Math.ceil((1280 / 621) * adjustedHeight),
      height: adjustedHeight,
    };
  }

  if (adjustedWidth / adjustedHeight > 1280 / 621) {
    return {
      width: Math.ceil(adjustedHeight * (1280 / 621)),
      height: adjustedHeight,
    };
  }

  return {
    width: adjustedWidth,
    height: Math.ceil(adjustedWidth * (621 / 1280)),
  };
});

const mapStyle = computed(() => {
  const style = {};
  style['--world-map-width'] = `${computedSize.value.width}px`;
  style['--world-map-height'] = `${computedSize.value.height}px`;
  return style;
});

const mapPoints = ref([]);
let computeMapPointsTimer = null;
function computeMapPoints() {
  if (computeMapPointsTimer) {
    clearTimeout(computeMapPointsTimer);
  }
  if (props.locations.length === 0) {
    mapPoints.value = [];
    return;
  }
  computeMapPointsTimer = setTimeout(() => {
    const points = props.locations.map((i) => {
      const item = {
        key: i.key,
        left: (computedSize.value.width / 1280) * i.x + boxPadding,
        top: (computedSize.value.height / 621) * i.y + boxPadding,
        size: i.size || 4,
        label: i.label,
        servers: i.servers,
        type: 'single',
      };
      const halfSize = (item.size + 8) / 2;
      item.topLeft = {
        left: item.left - halfSize,
        top: item.top - halfSize,
      };
      item.bottomRight = {
        left: item.left + halfSize,
        top: item.top + halfSize,
      };
      return item;
    });
    const groups = findIntersectingGroups(points);
    Object.entries(groups).forEach(([key, group]) => {
      const item = points.find((i) => i.key === key);
      if (item.parent) {
        return;
      }
      item.size = 4;
      item.type = 'group';
      item.children = group;
      let label = item.label || '';
      let servers = [...(item.servers || [])];
      group.forEach((i) => {
        if (!i.parent && !i.children) {
          i.parent = item;
          label += `\n${i.label}`;
          servers = servers.concat((i.servers || []));
        }
      });
      item.label = label;
      item.servers = servers;
    });
    mapPoints.value = points.filter((i) => !i.parent);
  }, 100);
}

watch(() => props.locations, () => {
  computeMapPoints();
}, {
  immediate: true,
});

watch(() => computedSize.value, () => {
  computeMapPoints();
}, {
  immediate: true,
  deep: true,
});

/**
 * 提示框
 */
const tipsShow = ref(false);
const tipsContent = ref('');
const activeTipsXY = ref({
  x: 0,
  y: 0,
});
const tipsContentStyle = computed(() => {
  const style = {};
  if (window.innerWidth > 500) {
    style.top = `${activeTipsXY.value.y}px`;
    style.left = `${activeTipsXY.value.x}px`;
    style.transform = 'translate(-50%, 20px)';
  } else {
    style.bottom = '4px';
    style.left = '50%';
    style.transform = 'translate(-50%, 0)';
  }
  return style;
});
let handlePointTapTimer = null;
function handlePointTap(e) {
  tipsContent.value = e.label;
  activeTipsXY.value = {
    x: e.left,
    y: e.top - 10,
  };
  tipsShow.value = true;
  if (handlePointTapTimer) {
    clearTimeout(handlePointTapTimer);
  }
  handlePointTapTimer = setTimeout(() => {
    tipsShow.value = false;
  }, 5000);
}
</script>

<style lang="scss" scoped>
.world-map-group {
  width: var(--world-map-width, 1280px);
  height: var(--world-map-height, 621px);
  position: relative;

  .world-map-img {
    width: var(--world-map-width, 1280px);
    height: var(--world-map-height, 621px);
    background: url(@/assets/images/world-map.svg) 50% 50% no-repeat;
    background-size: 100%;
    opacity: 0.75;
  }

  .world-map-tips {
    position: absolute;
    padding: 5px 10px;
    border-radius: 5px;
    line-height: 20px;
    white-space: pre;
    color: #eee;
    background: rgba(#000, 0.8);
    box-shadow: 1px 4px 8px rgba(#303841, 0.4);
    z-index: 100;

    // 向上的尖角
    &::before {
      content: '';
      position: absolute;
      bottom: 100%;
      left: 50%;
      width: 0;
      height: 0;
      border: 5px solid transparent;
      border-bottom-color: rgba(#000, 0.8);
      transform: translateX(-50%);
    }

    @media screen and (max-width: 500px) {
      line-height: 16px;
      font-size: 12px;

      &::before {
        display: none;
      }
    }
  }
}

.point-move,
.point-enter-active,
.point-leave-active {
  transition: opacity 0.3s ease-in-out;
}
.point-enter-from,
.point-leave-to {
  opacity: 0;
}
</style>
