// src/components/nazhua/WorldMap.tsx
import worldMapSvgUrl from "@/assets/images/world-map.svg"
import { alias2code, count2size, findIntersectingGroups, locationCode2Info, type WorldMapPointBox } from "@/lib/nazhua/world-map"
import { cn, parsePublicNote } from "@/lib/utils"
import type { NezhaServer } from "@/types/nezha-api"
import { useEffect, useMemo, useRef, useState, type CSSProperties } from "react"

type Location = {
  key: string
  x: number
  y: number
  size: number
  label: string
  servers: NezhaServer[]
}

function computeSize(width?: number, height?: number, boxPadding = 0) {
  const baseW = 1280
  const baseH = 621
  const adjustedW = (width ?? baseW) - boxPadding * 2
  const adjustedH = (height ?? baseH) - boxPadding * 2

  if (width != null && height != null) return { width: baseW, height: baseH }
  if (width != null && height == null) return { width: adjustedW, height: Math.ceil((baseH / baseW) * adjustedW) }
  if (width == null && height != null) return { width: Math.ceil((baseW / baseH) * adjustedH), height: adjustedH }
  if (adjustedW / adjustedH > baseW / baseH) return { width: Math.ceil(adjustedH * (baseW / baseH)), height: adjustedH }
  return { width: adjustedW, height: Math.ceil(adjustedW * (baseH / baseW)) }
}

function buildPoints(locations: Location[], width: number, height: number, boxPadding: number) {
  if (!locations.length) return [] as WorldMapPointBox[]
  const points: WorldMapPointBox[] = locations.map((i) => {
    const left = (width / 1280) * i.x + boxPadding
    const top = (height / 621) * i.y + boxPadding
    const size = i.size || 4
    const item: WorldMapPointBox = {
      key: i.key,
      left,
      top,
      size,
      label: i.label,
      servers: i.servers,
      type: "single",
      topLeft: { left: 0, top: 0 },
      bottomRight: { left: 0, top: 0 },
    }
    const halfSize = (item.size + 8) / 2
    item.topLeft = { left: item.left - halfSize, top: item.top - halfSize }
    item.bottomRight = { left: item.left + halfSize, top: item.top + halfSize }
    return item
  })

  const groups = findIntersectingGroups(points)
  Object.entries(groups).forEach(([key, group]) => {
    const item = points.find((p) => p.key === key)
    if (!item || item.parent) return
    item.size = 4
    item.type = "group"
    item.children = group
    let label = item.label || ""
    let servers = [...(item.servers as NezhaServer[])]
    group.forEach((g) => {
      if (!g.parent && !g.children) {
        g.parent = item
        label += `\n${g.label}`
        servers = servers.concat(g.servers as NezhaServer[])
      }
    })
    item.label = label
    item.servers = servers
  })

  return points.filter((p) => !p.parent)
}

export function serversToLocations(servers: NezhaServer[], now: number) {
  const locationMap: Record<string, NezhaServer[]> = {}
  servers.forEach((s) => {
    const lastActiveTime = s.last_active.startsWith("000") ? 0 : new Date(s.last_active).getTime()
    const online = now - lastActiveTime <= 30000
    if (!online) return

    const note = parsePublicNote(s.public_note || "")
    const location = note?.customData?.location
    const aliasCode = (typeof location === "string" ? location : undefined) || s.country_code?.toUpperCase()
    const code = alias2code(aliasCode) || aliasCode
    if (!code) return
    if (!locationMap[code]) locationMap[code] = []
    locationMap[code].push(s)
  })

  const locations: Location[] = []
  Object.entries(locationMap).forEach(([code, list]) => {
    const info = locationCode2Info(code)
    if (!info?.x || !info?.y) return
    locations.push({
      key: code,
      x: info.x,
      y: info.y,
      size: count2size(list.length),
      label: `${info.name},${list.length}台`,
      servers: list,
    })
  })
  return locations
}

export default function WorldMap({
  width,
  height,
  locations,
  className,
}: {
  width?: number
  height?: number
  locations: Location[]
  className?: string
}) {
  const boxPadding = 0
  const computed = useMemo(() => computeSize(width, height, boxPadding), [width, height, boxPadding])
  const points = useMemo(() => buildPoints(locations, computed.width, computed.height, boxPadding), [locations, computed.width, computed.height, boxPadding])

  const [tipsShow, setTipsShow] = useState(false)
  const [tipsContent, setTipsContent] = useState("")
  const [activeTipsXY, setActiveTipsXY] = useState({ x: 0, y: 0 })
  const timerRef = useRef<number | null>(null)

  useEffect(() => {
    return () => {
      if (timerRef.current) window.clearTimeout(timerRef.current)
    }
  }, [])

  const tipsStyle = useMemo(() => {
    const style: Record<string, string> = {}
    if (window.innerWidth > 500) {
      style.top = `${activeTipsXY.y}px`
      style.left = `${activeTipsXY.x}px`
      style.transform = "translate(-50%, 20px)"
    } else {
      style.bottom = "4px"
      style.left = "50%"
      style.transform = "translate(-50%, 0)"
    }
    return style
  }, [activeTipsXY])

  const onPointTap = (p: WorldMapPointBox) => {
    setTipsContent(p.label)
    setActiveTipsXY({ x: p.left, y: p.top - 10 })
    setTipsShow(true)
    if (timerRef.current) window.clearTimeout(timerRef.current)
    timerRef.current = window.setTimeout(() => setTipsShow(false), 5000)
  }

  return (
    <div
      className={cn("nazhua-world-map-group", className)}
      style={
        {
          ["--world-map-width"]: `${computed.width}px`,
          ["--world-map-height"]: `${computed.height}px`,
        } as CSSProperties & Record<string, string>
      }
    >
      <div className="nazhua-world-map-img" style={{ backgroundImage: `url(${worldMapSvgUrl})` }} />
      <div className="nazhua-world-map-point-container">
        {points.map((p) => (
          <button
            key={p.key}
            type="button"
            className={cn("nazhua-world-map-point", `nazhua-world-map-point--${p.type}`)}
            style={
              {
                ["--map-point-left"]: `${p.left}px`,
                ["--map-point-top"]: `${p.top}px`,
                ["--map-point-size"]: `${p.size}px`,
              } as CSSProperties & Record<string, string>
            }
            onClick={() => onPointTap(p)}
            aria-label={p.label}
          />
        ))}
      </div>

      {tipsShow ? (
        <div className="nazhua-world-map-tips" style={tipsStyle}>
          <span>{tipsContent}</span>
        </div>
      ) : null}
    </div>
  )
}

// src/components/world-map/world-map.vue
<template>
  <div
    class="world-map-group"
    :style="mapStyle"
  >
    <div class="world-map-img" />
    <transition-group
      name="point"
      tag="div"
      class="world-map-point-container"
    >
      <world-map-point
        v-for="pointItem in mapPoints"
        :key="pointItem.key"
        :info="pointItem"
        @point-tap="handlePointTap"
      />
    </transition-group>

    <transition name="point">
      <div
        v-if="tipsShow"
        class="world-map-tips"
        :style="tipsContentStyle"
      >
        <span>{{ tipsContent }}</span>
      </div>
    </transition>
  </div>
</template>

<script setup>
/**
 * 世界地图盒子
 */

import {
  ref,
  computed,
  watch,
} from 'vue';
import validate from '@/utils/validate';

import WorldMapPoint from './world-map-point.vue';
import {
  findIntersectingGroups,
} from '@/utils/world-map';

const props = defineProps({
  width: {
    type: [Number, String],
    // default: 1280,
    default: null,
  },
  height: {
    type: [Number, String],
    // default: 621,
    default: null,
  },
  locations: {
    type: Array,
    default: () => [],
  },
});

const boxPadding = 0;

// 计算地图大小 保持1280:621的比例 保证地图不变形
const computedSize = computed(() => {
  if (validate.isEmpty(props.width) && validate.isEmpty(props.height)) {
    return {
      width: 1280,
      height: 621,
    };
  }

  // 考虑内边距，从总宽高中减去padding
  const adjustedWidth = Number(props.width) - (boxPadding * 2);
  const adjustedHeight = Number(props.height) - (boxPadding * 2);

  if (!validate.isEmpty(props.width) && !validate.isEmpty(props.height)) {
    return {
      width: 1280,
      height: 621,
    };
  }

  if (!validate.isEmpty(props.width) && validate.isEmpty(props.height)) {
    return {
      width: adjustedWidth,
      height: Math.ceil((621 / 1280) * adjustedWidth),
    };
  }

  if (validate.isEmpty(props.width) && !validate.isEmpty(props.height)) {
    return {
      width: Math.ceil((1280 / 621) * adjustedHeight),
      height: adjustedHeight,
    };
  }

  if (adjustedWidth / adjustedHeight > 1280 / 621) {
    return {
      width: Math.ceil(adjustedHeight * (1280 / 621)),
      height: adjustedHeight,
    };
  }

  return {
    width: adjustedWidth,
    height: Math.ceil(adjustedWidth * (621 / 1280)),
  };
});

const mapStyle = computed(() => {
  const style = {};
  style['--world-map-width'] = `${computedSize.value.width}px`;
  style['--world-map-height'] = `${computedSize.value.height}px`;
  return style;
});

const mapPoints = ref([]);
let computeMapPointsTimer = null;
function computeMapPoints() {
  if (computeMapPointsTimer) {
    clearTimeout(computeMapPointsTimer);
  }
  if (props.locations.length === 0) {
    mapPoints.value = [];
    return;
  }
  computeMapPointsTimer = setTimeout(() => {
    const points = props.locations.map((i) => {
      const item = {
        key: i.key,
        left: (computedSize.value.width / 1280) * i.x + boxPadding,
        top: (computedSize.value.height / 621) * i.y + boxPadding,
        size: i.size || 4,
        label: i.label,
        servers: i.servers,
        type: 'single',
      };
      const halfSize = (item.size + 8) / 2;
      item.topLeft = {
        left: item.left - halfSize,
        top: item.top - halfSize,
      };
      item.bottomRight = {
        left: item.left + halfSize,
        top: item.top + halfSize,
      };
      return item;
    });
    const groups = findIntersectingGroups(points);
    Object.entries(groups).forEach(([key, group]) => {
      const item = points.find((i) => i.key === key);
      if (item.parent) {
        return;
      }
      item.size = 4;
      item.type = 'group';
      item.children = group;
      let label = item.label || '';
      let servers = [...(item.servers || [])];
      group.forEach((i) => {
        if (!i.parent && !i.children) {
          i.parent = item;
          label += `\n${i.label}`;
          servers = servers.concat((i.servers || []));
        }
      });
      item.label = label;
      item.servers = servers;
    });
    mapPoints.value = points.filter((i) => !i.parent);
  }, 100);
}

watch(() => props.locations, () => {
  computeMapPoints();
}, {
  immediate: true,
});

watch(() => computedSize.value, () => {
  computeMapPoints();
}, {
  immediate: true,
  deep: true,
});

/**
 * 提示框
 */
const tipsShow = ref(false);
const tipsContent = ref('');
const activeTipsXY = ref({
  x: 0,
  y: 0,
});
const tipsContentStyle = computed(() => {
  const style = {};
  if (window.innerWidth > 500) {
    style.top = `${activeTipsXY.value.y}px`;
    style.left = `${activeTipsXY.value.x}px`;
    style.transform = 'translate(-50%, 20px)';
  } else {
    style.bottom = '4px';
    style.left = '50%';
    style.transform = 'translate(-50%, 0)';
  }
  return style;
});
let handlePointTapTimer = null;
function handlePointTap(e) {
  tipsContent.value = e.label;
  activeTipsXY.value = {
    x: e.left,
    y: e.top - 10,
  };
  tipsShow.value = true;
  if (handlePointTapTimer) {
    clearTimeout(handlePointTapTimer);
  }
  handlePointTapTimer = setTimeout(() => {
    tipsShow.value = false;
  }, 5000);
}
</script>

<style lang="scss" scoped>
.world-map-group {
  width: var(--world-map-width, 1280px);
  height: var(--world-map-height, 621px);
  position: relative;

  .world-map-img {
    width: var(--world-map-width, 1280px);
    height: var(--world-map-height, 621px);
    background: url(@/assets/images/world-map.svg) 50% 50% no-repeat;
    background-size: 100%;
    opacity: 0.75;
  }

  .world-map-tips {
    position: absolute;
    padding: 5px 10px;
    border-radius: 5px;
    line-height: 20px;
    white-space: pre;
    color: #eee;
    background: rgba(#000, 0.8);
    box-shadow: 1px 4px 8px rgba(#303841, 0.4);
    z-index: 100;

    // 向上的尖角
    &::before {
      content: '';
      position: absolute;
      bottom: 100%;
      left: 50%;
      width: 0;
      height: 0;
      border: 5px solid transparent;
      border-bottom-color: rgba(#000, 0.8);
      transform: translateX(-50%);
    }

    @media screen and (max-width: 500px) {
      line-height: 16px;
      font-size: 12px;

      &::before {
        display: none;
      }
    }
  }
}

.point-move,
.point-enter-active,
.point-leave-active {
  transition: opacity 0.3s ease-in-out;
}
.point-enter-from,
.point-leave-to {
  opacity: 0;
}
</style>
