// src/layout/components/search-box.vue
<template>
  <transition name="fadeIn">
    <div
      v-if="show"
      class="search-box-background"
      @click="closeSearchBox"
    />
  </transition>
  <transition name="fadeIn">
    <div
      v-if="show"
      class="search-box-group"
    >
      <div class="search-box">
        <input
          ref="searchInputRef"
          v-model.trim="searchWord"
          type="text"
          placeholder="可搜索服务器名称、标签、系统、国别代码"
          class="search-box-input"
          @input="onSearchInput"
          @keydown.enter="onSearchInput"
          @blur="onSearchInput"
        />
        <span
          v-if="searchWord"
          class="clear-btn"
          @click="clearSearchWord"
        >
          <i class="clear-icon ri-close-fill" />
        </span>
      </div>
      <div class="result-server-list-container">
        <div class="search-list">
          <search-list-item
            v-for="item in searchResult"
            :key="item.ID"
            :info="item"
            @open-detail="openDetail"
          />
        </div>
      </div>
    </div>
  </transition>

  <div
    class="search-active-btn"
    @click="activeSearchBox"
  >
    <span class="icon">
      <i class="ri-search-line" />
    </span>
  </div>
</template>

<script setup>
/**
 * 搜索盒子
 */

import {
  computed,
  ref,
  onMounted,
  onUnmounted,
} from 'vue';
import {
  useStore,
} from 'vuex';
import {
  useRouter,
} from 'vue-router';

import SearchListItem from './search-list-item.vue';
import { getServerKey } from '@/utils/server-key';

const router = useRouter();
const store = useStore();
const serverList = computed(() => store.state.serverList);

const show = ref(false);
const searchWord = ref('');
const searchResult = ref([]);
const searchInputRef = ref(null);

let handleSearchTimer = null;
function handleSearch() {
  if (handleSearchTimer) {
    clearTimeout(handleSearchTimer);
  }
  if (!searchWord.value) {
    searchResult.value = [...serverList.value];
    return;
  }
  handleSearchTimer = setTimeout(() => {
    handleSearchTimer = null;
    searchResult.value = serverList.value.filter((item) => {
      {
        const matched = item.Name.toLowerCase().includes(searchWord.value.toLowerCase());
        if (matched) {
          return true;
        }
      }
      if (item?.PublicNote?.planDataMod) {
        const {
          networkRoute = '',
          extra = '',
        } = item.PublicNote.planDataMod;
        return [
          networkRoute.toLowerCase().includes(searchWord.value.toLowerCase()),
          extra.toLowerCase().includes(searchWord.value.toLowerCase()),
          (item.Host.Platform || '').toLowerCase().includes(searchWord.value.toLowerCase()),
          (item.Host.CountryCode || '').toLowerCase().includes(searchWord.value.toLowerCase()),
        ].some((match) => match);
      }
      return false;
    });
  }, 200);
}

function onSearchInput() {
  handleSearch();
}

function clearSearchWord() {
  searchWord.value = '';
  searchResult.value = [...serverList.value];
}

function activeSearchBox() {
  searchWord.value = '';
  searchResult.value = [...serverList.value];
  show.value = true;
  // 锁定页面滚动
  document.body.style.overflow = 'hidden';

  // 聚焦到搜索框
  setTimeout(() => {
    searchInputRef.value.focus();
  }, 30);
}

function closeSearchBox() {
  show.value = false;
  document.body.style.overflow = '';
}

function openDetail(info) {
  router.push({
    name: 'ServerDetail',
    params: {
      serverKey: getServerKey(info),
    },
  });
  closeSearchBox();
}

function handleKeyDown(event) {
  if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') {
    event.stopPropagation();
    event.preventDefault();
    if (show.value) {
      closeSearchBox();
    } else {
      activeSearchBox();
    }
  }
}

function handleEscKey(event) {
  if (!show.value) {
    return;
  }
  if (event.key === 'Escape') {
    closeSearchBox();
    event.stopPropagation();
    event.preventDefault();
  }
}

onMounted(() => {
  // 监听按下快捷键 Ctrl+K 打开搜索框
  window.addEventListener('keydown', handleKeyDown);
  // 监听按下 Esc 关闭搜索框
  window.addEventListener('keydown', handleEscKey);
});

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown);
  window.removeEventListener('keydown', handleEscKey);
  if (handleSearchTimer) {
    clearTimeout(handleSearchTimer);
    handleSearchTimer = null;
  }
});
</script>

<style lang="scss" scoped>
.search-box-background {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.15);
  z-index: 1000;
}

.search-box-group {
  position: fixed;
  left: 50%;
  top: 150px;
  z-index: 1010;
  transform: translate(-50%, 0);
  width: 600px;
  padding: 30px;
  border-radius: 12px;
  background-color: rgba(#000, 0.9);

  @media screen and (max-width: 640px) {
    width: auto;
    top: 100px;
    left: 20px;
    right: 20px;
    padding: 20px;
    transform: translate(0, 0);
  }

  .search-box {
    position: relative;
    width: 100%;
    padding-right: 40px;
    border-radius: 20px;
    background: #eee;

    .search-box-input {
      width: 100%;
      height: 40px;
      padding: 0 15px;
      color: #234;
      font-size: 14px;
      background: transparent;
      border: none;
      outline: none;
      transition: 0.3s;
    }

    .clear-btn {
      position: absolute;
      top: 0;
      right: 0;
      width: 40px;
      height: 40px;
      line-height: 40px;
      text-align: center;
      cursor: pointer;
      transition: 0.3s;

      .clear-icon {
        font-size: 20px;
        color: #666;
      }

      &:hover {
        color: #333;
      }
    }
  }

  .search-list {
    margin-top: 10px;
    height: 300px;
    overflow-x: hidden;
    overflow-y: auto;
    @media screen and (max-width: 640px) {
      height: 50vh;
    }

    &::-webkit-scrollbar {
      width: 8px;
    }

    &::-webkit-scrollbar-track {
      background: rgba(255, 255, 255, 0.1);
      border-radius: 4px;
    }

    &::-webkit-scrollbar-thumb {
      background: rgba(255, 255, 255, 0.3);
      border-radius: 4px;

      &:hover {
        background: rgba(255, 255, 255, 0.5);
      }
    }
  }
}

.search-active-btn {
  position: fixed;
  right: 20px;
  bottom: 20px;
  z-index: 10;
  width: 48px;
  height: 48px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 50%;
  background: rgba(#000, 0.7);
  cursor: pointer;
  transition: 0.3s;

  .icon {
    line-height: 1;
    font-size: 24px;
    color: #eee;
  }

  &:hover {
    background: rgba(#000, 0.9);
  }
}

.fadeIn-enter-active,
.fadeIn-leave-active {
  transition: opacity 0.3s ease-in-out;
}
.fadeIn-enter-from,
.fadeIn-leave-to {
  opacity: 0;
}
</style>

// src/components/SearchBox.tsx
import { useEffect, useMemo, useRef, useState } from "react"

import { useNavigate } from "react-router-dom"

import { useNezhaWsData } from "@/hooks/use-nezha-ws-data"
import { serverIdToServerKey } from "@/lib/server-key"
import { getServerSearchViewModel, matchServerSearchWord } from "@/lib/server-view-model"
import { type NezhaServer } from "@/types/nezha-api"

function buildTagList(server: NezhaServer) {
  return getServerSearchViewModel(server).tagList
}

function matchServer(server: NezhaServer, word: string) {
  return matchServerSearchWord(server, word)
}

function SearchListItem({ server, onOpenDetail }: { server: NezhaServer; onOpenDetail: (s: NezhaServer) => void }) {
  const tagList = useMemo(() => buildTagList(server), [server])
  return (
    <div className="search-list-item" onClick={() => onOpenDetail(server)}>
      <div className="server-name">{server.name}</div>
      {tagList.length > 0 ? (
        <div className="server-tag-list">
          {tagList.map((tag, idx) => (
            <span key={`${server.id}_tag_${idx}`} className="tag-item">
              {tag}
            </span>
          ))}
        </div>
      ) : null}
    </div>
  )
}

export default function SearchBox() {
  const navigate = useNavigate()
  const { data: parsedWsData, connected } = useNezhaWsData()

  const nezhaWsData = connected ? parsedWsData : null
  const serverList = useMemo(() => (nezhaWsData?.servers && Array.isArray(nezhaWsData.servers) ? nezhaWsData.servers : []), [nezhaWsData?.servers])

  const [show, setShow] = useState(false)
  const [searchWord, setSearchWord] = useState("")
  const [searchResult, setSearchResult] = useState<NezhaServer[]>([])
  const inputRef = useRef<HTMLInputElement | null>(null)

  const searchTimer = useRef<number | null>(null)

  function openSearch() {
    setSearchWord("")
    setSearchResult([...serverList])
    setShow(true)
    document.body.style.overflow = "hidden"
    window.setTimeout(() => inputRef.current?.focus(), 30)
  }

  function closeSearch() {
    setShow(false)
    document.body.style.overflow = ""
  }

  function clearSearchWord() {
    setSearchWord("")
    setSearchResult([...serverList])
  }

  function handleSearch(word: string) {
    if (searchTimer.current) window.clearTimeout(searchTimer.current)
    if (!word) {
      setSearchResult([...serverList])
      return
    }
    searchTimer.current = window.setTimeout(() => {
      searchTimer.current = null
      const list = serverList.filter((s) => matchServer(s, word))
      setSearchResult(list)
    }, 200)
  }

  function onOpenDetail(server: NezhaServer) {
    navigate(`/server/${serverIdToServerKey(server.id)}`)
    closeSearch()
  }

  useEffect(() => {
    function handleKeyDown(event: KeyboardEvent) {
      if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") {
        event.stopPropagation()
        event.preventDefault()
        if (show) closeSearch()
        else openSearch()
      }
    }

    function handleEscKey(event: KeyboardEvent) {
      if (!show) return
      if (event.key === "Escape") {
        event.stopPropagation()
        event.preventDefault()
        closeSearch()
      }
    }

    window.addEventListener("keydown", handleKeyDown)
    window.addEventListener("keydown", handleEscKey)
    return () => {
      window.removeEventListener("keydown", handleKeyDown)
      window.removeEventListener("keydown", handleEscKey)
    }
  }, [show, serverList])

  useEffect(() => {
    if (!show) return
    handleSearch(searchWord)
  }, [searchWord])

  useEffect(() => {
    if (!show) return
    setSearchResult([...serverList])
  }, [serverList, show])

  useEffect(
    () => () => {
      if (searchTimer.current) window.clearTimeout(searchTimer.current)
      document.body.style.overflow = ""
    },
    [],
  )

  if (!serverList.length) {
    return null
  }

  return (
    <>
      {show ? <div className="search-box-background" onClick={closeSearch} /> : null}
      {show ? (
        <div className="search-box-group">
          <div className="search-box">
            <input
              ref={inputRef}
              value={searchWord}
              type="text"
              placeholder="可搜索服务器名称、标签、系统、国别代码"
              className="search-box-input"
              onChange={(e) => setSearchWord(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter") handleSearch(searchWord)
              }}
              onBlur={() => handleSearch(searchWord)}
            />
            {searchWord ? (
              <span className="clear-btn" onClick={clearSearchWord}>
                <i className="clear-icon ri-close-fill" />
              </span>
            ) : null}
          </div>
          <div className="result-server-list-container">
            <div className="search-list">
              {searchResult.map((item) => (
                <SearchListItem key={item.id} server={item} onOpenDetail={onOpenDetail} />
              ))}
            </div>
          </div>
        </div>
      ) : null}

      <div className="search-active-btn" onClick={openSearch} title="搜索 (Ctrl/Cmd+K)">
        <span className="icon">
          <i className="ri-search-line" />
        </span>
      </div>
    </>
  )
}
