// src/views/components/server-list/server-option-box.vue
<template>
  <div
    class="server-option-box"
    :class="{
      'server-option-box--mobile-hide': !mobileShow,
    }"
  >
    <div
      v-for="item in options"
      :key="item.key"
      class="server-option-item"
      :class="{
        'has-icon': item.icon,
        active: activeValue === item.value,
      }"
      :title="item?.title || false"
      @click="toggleModelValue(item)"
    >
      <i
        v-if="item.icon"
        class="option-icon"
        :class="item.icon"
        :title="item.label"
      />
      <span
        v-else
        class="option-label"
      >{{ item.label }}</span>
    </div>
  </div>
</template>

<script setup>
/**
 * 过滤栏
 */
import {
  computed,
} from 'vue';

const props = defineProps({
  modelValue: {
    type: [String, Number],
    default: '',
  },
  options: {
    type: Array,
    default: () => [],
  },
  acceptEmpty: {
    type: Boolean,
    default: true,
  },
  mobileShow: {
    type: Boolean,
    default: true,
  },
});

const emits = defineEmits([
  'update:modelValue',
]);

const activeValue = computed({
  get: () => props.modelValue,
  set: (val) => {
    emits('update:modelValue', val);
  },
});

function toggleModelValue(item) {
  if (activeValue.value === item.value) {
    if (props.acceptEmpty) {
      activeValue.value = '';
    }
  } else {
    activeValue.value = item.value;
  }
}
</script>

<style lang="scss" scoped>
.server-option-box {
  display: flex;
  flex-wrap: wrap;
  padding: 0 var(--list-padding);
  gap: 8px;

  @media screen and (max-width: 768px) {
    &--mobile-hide {
      display: none;
    }
  }

  .server-option-item {
    display: flex;
    align-items: center;
    height: 36px;
    padding: 0 15px;
    line-height: 1.2;
    border-radius: 6px;
    background: rgba(#000, 0.3);
    transition: all 0.3s linear;
    cursor: pointer;

    &.has-icon {
      padding: 0 10px;
    }

    @media screen and (max-width: 768px) {
      height: 30px;
      padding: 0 10px;
      border-radius: 3px;
      background-color: rgba(#000, 0.8);
      cursor: default;
    }

    .option-icon {
      line-height: 1;
      font-size: 18px;
    }

    .option-label {
      color: #fff;
      font-weight: bold;
      transition: all 0.3s linear;
    }

    @media screen and (min-width: 768px) {
      &:hover {
        .option-label {
          color: var(--option-high-color);
        }
      }
    }

    &.active {
      background: var(--option-high-color-active);

      .option-label {
        color: #fff;
      }
    }
  }

}
</style>

// src/components/ServerOptionBox.tsx
import { useMemo } from "react"

import { cn } from "@/lib/utils"

export type ServerOptionItem = {
  key: string
  label: string
  value: string
  title?: string
  icon?: string
}

export function ServerOptionBox({
  value,
  onChange,
  options,
  acceptEmpty = true,
  mobileShow = true,
  className,
}: {
  value: string
  onChange: (val: string) => void
  options: ServerOptionItem[]
  acceptEmpty?: boolean
  mobileShow?: boolean
  className?: string
}) {
  const activeValue = value ?? ""
  const safeOptions = useMemo(() => (Array.isArray(options) ? options : []), [options])

  function toggleModelValue(item: ServerOptionItem) {
    if (activeValue === item.value) {
      if (acceptEmpty) onChange("")
      return
    }
    onChange(item.value)
  }

  return (
    <div
      className={cn(
        "server-option-box",
        {
          "server-option-box--mobile-hide": !mobileShow,
        },
        className,
      )}
    >
      {safeOptions.map((item) => (
        <div
          key={item.key}
          className={cn("server-option-item", {
            "has-icon": !!item.icon,
            "active": activeValue === item.value,
          })}
          title={item.title || undefined}
          onClick={() => toggleModelValue(item)}
        >
          {item.icon ? (
            <i className={cn("option-icon", item.icon)} title={item.label} />
          ) : (
            <span className="option-label">{item.label}</span>
          )}
        </div>
      ))}
    </div>
  )
}
